import Head from "next/head";
import Product from "../components/Product/Product";
import styles from "../styles/Home.module.css";
import { getAll } from "../services/directus/utils";
import { UseUxContext } from "../contexts/uxContext";
import Flash from "../components/Flash/Flash";

export async function getStaticProps() {
  const products = await getAll("product");
  const categories = await getAll("category");
  return {
    props: {
      products: products,
      categories: categories,
    },
    revalidate: 10,
  };
}

// export async function getServerSideProps() {
//   // Fetch data from external API
//   const res = await fetch(`${process.env.HOST}/api/products`);
//   const products = await res.json();

//   // Pass data to the page via props
//   return { props: { products } };
// }

export default function Home({ products }) {
  const { flash, flashType } = UseUxContext();

  return (
    <>
      <Head>
        <title>Indication | Nom de Marque</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1>Produits</h1>
        <div className={styles.products}>{products && products.map((p) => <Product key={p.id} product={p} />)}</div>
        {flash && <Flash type={flashType} text={flash} />}
      </main>
    </>
  );
}
