import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { getAllCategories } from "../lib/directus/categories";
import { useCartStore } from "../contexts/cartStore";
import useEffectOnce from "../hooks/useEffectOnce";

export async function getStaticProps() {
  const categories = await getAllCategories();
  return {
    props: {
      categories: categories,
    },
    revalidate: 10,
  };
}

const Confirmed = () => {
  const clear = useCartStore((state) => state.clearCart);

  useEffectOnce(() => {
    clear();
  });

  return (
    <>
      <Head>
        <title>Paiement Validé | Nom de Marque</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1>Paiement Validé</h1>
        <p>
          Merci pour votre commande, vous allez bientôt recevoir un mail confirmant votre paiement et contenant votre facture
          et votre suivi de livraison
        </p>
      </main>
    </>
  );
};

export default Confirmed;
