import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getAll } from "../services/directus/utils";
import { useEffect } from "react";

export async function getStaticProps() {
  const categories = await getAll("category");
  return {
    props: {
      categories: categories,
    },
    revalidate: 10,
  };
}

export default function Confirmed() {
  useEffect(() => {
    localStorage.setItem("cart", JSON.stringify([]));
  }, []);
  return (
    <>
      <Head>
        <title>Paiement Validé | Nom de Marque</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1>Paiement Validé</h1>
        <p>
          Merci pour votre commande, vous allez bientôt recevoir un mail confirmant votre paiement et contenant votre facture
          et votre suivi de livraison
        </p>
      </main>
    </>
  );
}
